from enum import Enum

class ChannelType(str, Enum):
    VOICE = "VOICE"
    SMS = "SMS"
    ZALO = "ZALO"
    EMAIL = "EMAIL"
    APP_NOTIFICATION = "APP_NOTIFICATION"
    FIELD_VISIT = "FIELD_VISIT"
    LEGAL_NOTICE = "LEGAL_NOTICE"


class CaseStatus(str, Enum):
    CREATED = "CREATED"
    ASSIGNED = "ASSIGNED"
    IN_TREATMENT = "IN_TREATMENT"
    PTP_SCHEDULED = "PTP_SCHEDULED"
    PTP_KEPT = "PTP_KEPT"
    PTP_BROKEN = "PTP_BROKEN"
    RESTRUCTURE_PENDING = "RESTRUCTURE_PENDING"
    RESTRUCTURE_APPROVED = "RESTRUCTURE_APPROVED"
    LEGAL_ESCALATED = "LEGAL_ESCALATED"
    RESOLVED_CURED = "RESOLVED_CURED"
    SETTLED_WRITEOFF = "SETTLED_WRITEOFF"
    CLOSED = "CLOSED"


class ExperimentArm(str, Enum):
    TREATED = "TREATED"      # 90% nhận chiến lược mới B.Collection
    CONTROL = "CONTROL"      # 10% Holdout Group đo lường Uplift
    CHAMPION = "CHAMPION"    # Chiến lược chuẩn hiện hành


class NegotiationLeverEnum(str, Enum):
    CIC_CREDIT_RECORD = "CIC_CREDIT_RECORD"
    ACCRUING_PENALTY_COST = "ACCRUING_PENALTY_COST"
    COLLATERAL_ENFORCEMENT_RISK = "COLLATERAL_ENFORCEMENT_RISK"
    LITIGATION_COST_TIME = "LITIGATION_COST_TIME"
    CORPORATE_CREDIT_RELATIONSHIP = "CORPORATE_CREDIT_RELATIONSHIP"
    EARLY_SETTLEMENT_DISCOUNT = "EARLY_SETTLEMENT_DISCOUNT"
    INTEREST_WAIVER_OFFER = "INTEREST_WAIVER_OFFER"
    RESTRUCTURE_OPPORTUNITY = "RESTRUCTURE_OPPORTUNITY"
    CASH_FLOW_TIMING = "CASH_FLOW_TIMING"
    COLLATERAL_RELEASE_INCENTIVE = "COLLATERAL_RELEASE_INCENTIVE"


class RootCausePrimaryEnum(str, Enum):
    FORGOT_OR_ADMIN = "FORGOT_OR_ADMIN"
    CASHFLOW_TIMING = "CASHFLOW_TIMING"
    INCOME_LOSS = "INCOME_LOSS"
    BUSINESS_DOWNTURN = "BUSINESS_DOWNTURN"
    OVER_INDEBTED = "OVER_INDEBTED"
    FORCE_MAJEURE = "FORCE_MAJEURE"
    HEALTH_OR_FAMILY_EVENT = "HEALTH_OR_FAMILY_EVENT"
    DISPUTE = "DISPUTE"
    FRAUD_VICTIM = "FRAUD_VICTIM"
    COLLATERAL_ISSUE = "COLLATERAL_ISSUE"
    WILFUL_DEFAULT = "WILFUL_DEFAULT"
    UNREACHABLE = "UNREACHABLE"
    UNKNOWN = "UNKNOWN"
